# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.24)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS osqp::osqpstatic osqp::osqp)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target osqp::osqpstatic
add_library(osqp::osqpstatic STATIC IMPORTED)

set_target_properties(osqp::osqpstatic PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/OxfordSolver/osqp/include"
)

# Create imported target osqp::osqp
add_library(osqp::osqp SHARED IMPORTED)

set_target_properties(osqp::osqp PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/OxfordSolver/osqp/include"
)

# Import target "osqp::osqpstatic" for configuration "Debug"
set_property(TARGET osqp::osqpstatic APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(osqp::osqpstatic PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "D:/Nuevo_Build_OSQP/out/Debug/osqp.lib"
  )

# Import target "osqp::osqp" for configuration "Debug"
set_property(TARGET osqp::osqp APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(osqp::osqp PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Nuevo_Build_OSQP/out/Debug/osqp.lib"
  IMPORTED_LOCATION_DEBUG "D:/Nuevo_Build_OSQP/out/Debug/osqp.dll"
  )

# Import target "osqp::osqpstatic" for configuration "Release"
set_property(TARGET osqp::osqpstatic APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(osqp::osqpstatic PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "D:/Nuevo_Build_OSQP/out/Release/osqp.lib"
  )

# Import target "osqp::osqp" for configuration "Release"
set_property(TARGET osqp::osqp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(osqp::osqp PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Nuevo_Build_OSQP/out/Release/osqp.lib"
  IMPORTED_LOCATION_RELEASE "D:/Nuevo_Build_OSQP/out/Release/osqp.dll"
  )

# Import target "osqp::osqpstatic" for configuration "MinSizeRel"
set_property(TARGET osqp::osqpstatic APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(osqp::osqpstatic PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "D:/Nuevo_Build_OSQP/out/MinSizeRel/osqp.lib"
  )

# Import target "osqp::osqp" for configuration "MinSizeRel"
set_property(TARGET osqp::osqp APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(osqp::osqp PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/Nuevo_Build_OSQP/out/MinSizeRel/osqp.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/Nuevo_Build_OSQP/out/MinSizeRel/osqp.dll"
  )

# Import target "osqp::osqpstatic" for configuration "RelWithDebInfo"
set_property(TARGET osqp::osqpstatic APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(osqp::osqpstatic PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/Nuevo_Build_OSQP/out/RelWithDebInfo/osqp.lib"
  )

# Import target "osqp::osqp" for configuration "RelWithDebInfo"
set_property(TARGET osqp::osqp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(osqp::osqp PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/Nuevo_Build_OSQP/out/RelWithDebInfo/osqp.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/Nuevo_Build_OSQP/out/RelWithDebInfo/osqp.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
