
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/CMAKE/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:5 (project)"
    message: |
      The system is: Windows - 10.0.19044 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "D:/CMAKE/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/CMAKE/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/CMAKE/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:5 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.5.1+f6fdcf537 for .NET Framework
      Build started 05/06/2023 11:25:39.
      Included response file: D:\\Visual studio\\MSBuild\\Current\\Bin\\amd64\\MSBuild.rsp
      
      Project "D:\\Nuevo_Build_OSQP\\CMakeFiles\\3.26.3\\CompilerIdC\\CompilerIdC.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        D:\\Visual studio\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        D:\\Visual studio\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> D:\\Nuevo_Build_OSQP\\CMakeFiles\\3.26.3\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=D:\\Visual studio\\VC\\Tools\\MSVC\\14.35.32215\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Deleting file "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
        Touching "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Done Building Project "D:\\Nuevo_Build_OSQP\\CMakeFiles\\3.26.3\\CompilerIdC\\CompilerIdC.vcxproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:04.71
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        D:/Nuevo_Build_OSQP/CMakeFiles/3.26.3/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/CMAKE/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/CMAKE/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/CMAKE/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:5 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.5.1+f6fdcf537 for .NET Framework
      Build started 05/06/2023 11:25:45.
      Included response file: D:\\Visual studio\\MSBuild\\Current\\Bin\\amd64\\MSBuild.rsp
      
      Project "D:\\Nuevo_Build_OSQP\\CMakeFiles\\3.26.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        D:\\Visual studio\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        D:\\Visual studio\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> D:\\Nuevo_Build_OSQP\\CMakeFiles\\3.26.3\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=D:\\Visual studio\\VC\\Tools\\MSVC\\14.35.32215\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Deleting file "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
        Touching "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Done Building Project "D:\\Nuevo_Build_OSQP\\CMakeFiles\\3.26.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:03.70
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        D:/Nuevo_Build_OSQP/CMakeFiles/3.26.3/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/CMAKE/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/CMAKE/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:5 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "D:/Nuevo_Build_OSQP/CMakeFiles/CMakeScratch/TryCompile-p57txk"
      binary: "D:/Nuevo_Build_OSQP/CMakeFiles/CMakeScratch/TryCompile-p57txk"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: D:/Nuevo_Build_OSQP/CMakeFiles/CMakeScratch/TryCompile-p57txk
        
        Run Build Command(s):D:/Visual studio/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_66ed3.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && MSBuild version 17.5.1+f6fdcf537 for .NET Framework
        Build started 05/06/2023 11:25:52.
        Included response file: D:\\Visual studio\\MSBuild\\Current\\Bin\\amd64\\MSBuild.rsp
        
        Project "D:\\Nuevo_Build_OSQP\\CMakeFiles\\CMakeScratch\\TryCompile-p57txk\\cmTC_66ed3.vcxproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "cmTC_66ed3.dir\\Debug\\".
          Creating directory "D:\\Nuevo_Build_OSQP\\CMakeFiles\\CMakeScratch\\TryCompile-p57txk\\Debug\\".
          Creating directory "cmTC_66ed3.dir\\Debug\\cmTC_66ed3.tlog\\".
        InitializeBuildStatus:
          Creating "cmTC_66ed3.dir\\Debug\\cmTC_66ed3.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        ClCompile:
          D:\\Visual studio\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_66ed3.dir\\Debug\\\\" /Fd"cmTC_66ed3.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "D:\\CMAKE\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.35.32217.1 for x64
          Copyright (C) Microsoft Corporation.  All rights reserved.
          CMakeCCompilerABI.c
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_66ed3.dir\\Debug\\\\" /Fd"cmTC_66ed3.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "D:\\CMAKE\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
        Link:
          D:\\Visual studio\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\Nuevo_Build_OSQP\\CMakeFiles\\CMakeScratch\\TryCompile-p57txk\\Debug\\cmTC_66ed3.exe" /INCREMENTAL /ILK:"cmTC_66ed3.dir\\Debug\\cmTC_66ed3.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/Nuevo_Build_OSQP/CMakeFiles/CMakeScratch/TryCompile-p57txk/Debug/cmTC_66ed3.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/Nuevo_Build_OSQP/CMakeFiles/CMakeScratch/TryCompile-p57txk/Debug/cmTC_66ed3.lib" /MACHINE:X64  /machine:x64 cmTC_66ed3.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_66ed3.vcxproj -> D:\\Nuevo_Build_OSQP\\CMakeFiles\\CMakeScratch\\TryCompile-p57txk\\Debug\\cmTC_66ed3.exe
        FinalizeBuildStatus:
          Deleting file "cmTC_66ed3.dir\\Debug\\cmTC_66ed3.tlog\\unsuccessfulbuild".
          Touching "cmTC_66ed3.dir\\Debug\\cmTC_66ed3.tlog\\cmTC_66ed3.lastbuildstate".
        Done Building Project "D:\\Nuevo_Build_OSQP\\CMakeFiles\\CMakeScratch\\TryCompile-p57txk\\cmTC_66ed3.vcxproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:03.98
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "D:/CMAKE/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "D:/CMAKE/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:5 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "D:/Nuevo_Build_OSQP/CMakeFiles/CMakeScratch/TryCompile-u042bn"
      binary: "D:/Nuevo_Build_OSQP/CMakeFiles/CMakeScratch/TryCompile-u042bn"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: D:/Nuevo_Build_OSQP/CMakeFiles/CMakeScratch/TryCompile-u042bn
        
        Run Build Command(s):D:/Visual studio/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_dc78e.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && MSBuild version 17.5.1+f6fdcf537 for .NET Framework
        Build started 05/06/2023 11:25:58.
        Included response file: D:\\Visual studio\\MSBuild\\Current\\Bin\\amd64\\MSBuild.rsp
        
        Project "D:\\Nuevo_Build_OSQP\\CMakeFiles\\CMakeScratch\\TryCompile-u042bn\\cmTC_dc78e.vcxproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "cmTC_dc78e.dir\\Debug\\".
          Creating directory "D:\\Nuevo_Build_OSQP\\CMakeFiles\\CMakeScratch\\TryCompile-u042bn\\Debug\\".
          Creating directory "cmTC_dc78e.dir\\Debug\\cmTC_dc78e.tlog\\".
        InitializeBuildStatus:
          Creating "cmTC_dc78e.dir\\Debug\\cmTC_dc78e.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        ClCompile:
          D:\\Visual studio\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_dc78e.dir\\Debug\\\\" /Fd"cmTC_dc78e.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "D:\\CMAKE\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.35.32217.1 for x64
          Copyright (C) Microsoft Corporation.  All rights reserved.
          CMakeCXXCompilerABI.cpp
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_dc78e.dir\\Debug\\\\" /Fd"cmTC_dc78e.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "D:\\CMAKE\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          D:\\Visual studio\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"D:\\Nuevo_Build_OSQP\\CMakeFiles\\CMakeScratch\\TryCompile-u042bn\\Debug\\cmTC_dc78e.exe" /INCREMENTAL /ILK:"cmTC_dc78e.dir\\Debug\\cmTC_dc78e.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"D:/Nuevo_Build_OSQP/CMakeFiles/CMakeScratch/TryCompile-u042bn/Debug/cmTC_dc78e.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"D:/Nuevo_Build_OSQP/CMakeFiles/CMakeScratch/TryCompile-u042bn/Debug/cmTC_dc78e.lib" /MACHINE:X64  /machine:x64 cmTC_dc78e.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_dc78e.vcxproj -> D:\\Nuevo_Build_OSQP\\CMakeFiles\\CMakeScratch\\TryCompile-u042bn\\Debug\\cmTC_dc78e.exe
        FinalizeBuildStatus:
          Deleting file "cmTC_dc78e.dir\\Debug\\cmTC_dc78e.tlog\\unsuccessfulbuild".
          Touching "cmTC_dc78e.dir\\Debug\\cmTC_dc78e.tlog\\cmTC_dc78e.lastbuildstate".
        Done Building Project "D:\\Nuevo_Build_OSQP\\CMakeFiles\\CMakeScratch\\TryCompile-u042bn\\cmTC_dc78e.vcxproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:03.24
        
      exitCode: 0
...
